//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConWebService.ServiceBlog {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBlog.IBlogSvc")]
    public interface IBlogSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogSvc/Crear", ReplyAction="http://tempuri.org/IBlogSvc/CrearResponse")]
        bool Crear(string xmlPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogSvc/Crear", ReplyAction="http://tempuri.org/IBlogSvc/CrearResponse")]
        System.Threading.Tasks.Task<bool> CrearAsync(string xmlPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogSvc/ListarTodo", ReplyAction="http://tempuri.org/IBlogSvc/ListarTodoResponse")]
        string ListarTodo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogSvc/ListarTodo", ReplyAction="http://tempuri.org/IBlogSvc/ListarTodoResponse")]
        System.Threading.Tasks.Task<string> ListarTodoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlogSvcChannel : AppConWebService.ServiceBlog.IBlogSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlogSvcClient : System.ServiceModel.ClientBase<AppConWebService.ServiceBlog.IBlogSvc>, AppConWebService.ServiceBlog.IBlogSvc {
        
        public BlogSvcClient() {
        }
        
        public BlogSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlogSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Crear(string xmlPost) {
            return base.Channel.Crear(xmlPost);
        }
        
        public System.Threading.Tasks.Task<bool> CrearAsync(string xmlPost) {
            return base.Channel.CrearAsync(xmlPost);
        }
        
        public string ListarTodo() {
            return base.Channel.ListarTodo();
        }
        
        public System.Threading.Tasks.Task<string> ListarTodoAsync() {
            return base.Channel.ListarTodoAsync();
        }
    }
}
